#################################################
# Gest configurations
#################################################
---
- hosts: proc
  become: yes
  vars_files:
    - group_vars/baremetal_hosts

  tasks:
    - name: Install unzip - it will be used by drush make
      become: true
      apt:
        name: unzip
        update_cache: yes
        state: present
      tags: build
      register: out

    - debug: var=out.stdout_lines
      tags: [unzip]

    - name: Install unzip default-jre
      become: true
      apt:
        name: default-jre
        update_cache: yes
        state: present
      tags: build
      register: out

    - debug: var=out.stdout_lines
      tags: [java]

    - name: Set APCu
      become: true
      apt:
        name: php-apcu
        update_cache: yes
        state: present
      tags: [apt_apcu]
      register: out
    
    - debug: var=out.stdout_lines
      tags: [apt_apcu]

    - name: Set mbstring
      become: true
      apt:
        name: php-mbstring
        update_cache: yes
        state: present
      tags: [apt_mbstring]
      register: out

    - debug: var=out.stdout_lines
      tags: [apt_apcu]

    - name: Set php json
      become: true
      apt:
        name: php-json
        update_cache: yes
        state: present
      tags: [apt_mbstring]
      register: out

    - debug: var=out.stdout_lines
      tags: [apt_phpjson]

    - name: Set imap
      become: true
      apt:
        name: php-imap
        update_cache: yes
        state: present
      tags: [apt_imap]
      register: out

    - debug: var=out.stdout_lines
      tags: [apt_phpjson]

# Set swp file:
# Reference: https://bogdancornianu.com/change-swap-size-in-ubuntu/
# sudo swapoff -a
## For 8 GB:
# sudo dd if=/dev/zero of=/swapfile bs=1G count=8
# sudo chmod 600 /swapfile
# sudo mkswap /swapfile
# sudo swapon /swapfile
## Edit /etc/fstab and add the new swapfile if it isn’t already there
# /swapfile none swap sw 0 0
## Check result:
# grep SwapTotal /proc/meminfo

  pre_tasks:
    # - name: Copy proxy settings
    #   shell: cp -ar /vagrant_data/assets/environment /etc/
    #   become: true      
    #   register: out
    #   args:
    #     chdir: /
    #   tags: sapi

    # - debug: var=out.stdout_lines
    #   tags: proxy
    - name: sudo apt update
      become: true
      apt:
        update_cache: yes
      tags: [apt]

    - name: sudo apt install ca-certificates apt-transport-https software-properties-common lsb-release -y
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ca-certificates
        - apt-transport-https
        - software-properties-common
        - lsb-release
      tags: [apt]

    - name: sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
      become: true
      shell: sysctl -w net.ipv6.conf.all.disable_ipv6=1
      tags: [ipv6]

    - name: sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
      become: true
      shell: sysctl -w net.ipv6.conf.default.disable_ipv6=1
      tags: [ipv6]

    - name: sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
      become: true
      shell: sysctl -w net.ipv6.conf.lo.disable_ipv6=1
      tags: [ipv6]

    - name: sudo add-apt-repository ppa:ondrej/php -y
      become: true
      apt_repository:
        repo: ppa:ondrej/php
        state: present
      tags: [apt]

    - name: sudo apt update
      become: true
      apt:
        update_cache: yes
      tags: [apt]

    - name: sudo apt upgrade
      become: true
      apt:
        upgrade: dist
      tags: [apt]

    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=86400

    - name: APT Update
      shell: "apt-get update -y"
      become: true
      register: out

    - debug: var=out.stdout_lines

    - name: APT Update
      shell: "apt-get update -y"
      become: true
      register: out

    - debug: var=out.stdout_lines

    - name: APT Update
      shell: "apt-get update -y"
      become: true
      register: out

    - debug: var=out.stdout_lines

    - name: APT install php-dev
      shell: "apt-get install -y php-dev"
      become: true
      register: out

    - debug: var=out.stdout_lines

    - name: APT install composer
      shell: "apt install -y composer"
      become: true
      register: out

    - debug: var=out.stdout_lines

    # - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
    #   community.crypto.openssl_privatekey:
    #     path: /etc/ssl/private/ansible.com.pem
    #   tags: [crypto]


  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php, tags: [ 'php' ] }
    - { role: geerlingguy.mysql, tags: [ 'mysql' ] }
    - { role: geerlingguy.php-mysql, tags: [ 'php-mysql' ] }
    - { role: geerlingguy.adminer, tags: [ 'adminer' ] }
    - { role: geerlingguy.adminer, tags: [ 'adminer' ] }
    - { role: geerlingguy.java }
    # - { role: geerlingguy.solr }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.drush }
    - { role: geerlingguy.htpasswd, tags: [ 'htpasswd' ]}
    # - { role: geerlingguy.php-xdebug }

# @TODO: add zend_extension=/usr/lib/php/20170718/xdebug.so
# to /etc/php/7.2/apache2/php.ini
# Also add to /etc/php/7.2/apache2/php.ini
# [XDebug]
# xdebug.remote_enable = 1
# xdebug.remote_autostart = 1

  post_tasks:

    - name: Add www-data user to vagrant group
      command: usermod -a -G vagrant www-data
      register: out

    - debug: var=out.stdout_lines

    - name: Restart apache for enabling MySQL
      command: systemctl restart apache2
      register: out

    - debug: var=out.stdout_lines

    # Restart apache:
    - name: Restart apache
      command: service apache2 restart
      become: true
      register: out
  
    - debug: var=out.stdout_lines

# @TODO: add baremetal.conf to /etc/apache2/sites-available
# <Directory /var/www/html/proclab/web/>
#         Options Indexes FollowSymLinks
#         AllowOverride All
#         Require all granted
# </Directory>
# and enable it using:
# sudo a2enconf baremetal.conf

# @TODO: add Directoy at default host for clean URL:
# <Directory /var/www/html>
#   Options Indexes FollowSymLinks MultiViews
#   AllowOverride All
#   Require all granted
#   AuthType Basic
#   AuthName "Apache with basic auth."
#   AuthUserFile /etc/apache-passwdfile
#   Require valid-user
# </Directory>
# /etc/apache2/sites-enabled/000-default.conf
# @TODO: set http password using:
# https://github.com/geerlingguy/ansible-role-htpasswd


# # @todo: add as a pre task, to be run in the host
# - name: ssh-keygen
#   shell: ssh-keygen -f /home/{{ baremetal_host_username }}/.ssh/known_hosts -R [127.0.0.1]:2222
#   register: out
#   tags: host_authoized_key_purge

# - debug: var=out.stdout_lines
#   tags: host_authoized_key_purge
# Configuration for Search API for C9/AWS/DIGIT
# Get at admin/config/search/search_api/server/solr_server/edit and configure:
#     HTTP protocol: 
#     Solr Host: 127.0.0.1
#     Solr port: 8983
#     Solr path:  /solr/d7_search_api
# Configuration for Search API for Baremetal/Vagrant
# Get at admin/config/search/search_api/server/solr_server/edit and configure:
#     HTTP protocol: 
#     Solr Host: 127.0.0.1
#     Solr port: 8983
#     Solr path:  /solr/collection1

