#################################################
# Gest configurations
#################################################
---
- hosts: emnies
  become: yes
  vars_files:
    - group_vars/emnies_hosts

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php, tags: [ 'php' ] }
    - { role: geerlingguy.mysql, tags: [ 'mysql' ] }
    - { role: geerlingguy.php-mysql, tags: [ 'php-mysql' ] }
    - { role: geerlingguy.adminer, tags: [ 'adminer' ] }
    - { role: geerlingguy.java }
    - { role: geerlingguy.solr }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.drush }

  post_tasks:

    - name: Restart apache for enabling MySQL
      command: apache2ctl restart
      register: out

    - debug: var=out.stdout_lines
