#################################################
# Gest configurations
#################################################
---
- hosts: db
  become: yes
  vars_files:
    - group_vars/emnies_hosts

  tasks:
    - name: Set APCu
      become: true
      apt:
        name: php7.2-apcu
        update_cache: yes
        state: present
      tags: [apt_apcu]
      register: out
    
    - debug: var=out.stdout_lines
      tags: [apt_apcu]

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php, tags: [ 'php' ] }
    - { role: geerlingguy.mysql, tags: [ 'mysql' ] }
    - { role: geerlingguy.php-mysql, tags: [ 'php-mysql' ] }
    - { role: geerlingguy.adminer, tags: [ 'adminer' ] }

  post_tasks:
    - name: Restart apache for enabling MySQL
      command: apache2ctl restart
      register: out

    - debug: var=out.stdout_lines

    # @TODO: add Directoy at default host for clean URL:
    # <Directory /var/www/html>
    #   Options Indexes FollowSymLinks MultiViews
    #   AllowOverride All
    #   Require all granted
    # </Directory>
    # /etc/apache2/sites-enabled/000-default.conf

# Set swp file:
# Reference: https://bogdancornianu.com/change-swap-size-in-ubuntu/
# sudo swapoff -a
## For 8 GB:
# sudo dd if=/dev/zero of=/swapfile bs=1G count=8
# sudo chmod 600 /swapfile
# sudo mkswap /swapfile
# sudo swapon /swapfile
## Edit /etc/fstab and add the new swapfile if it isn’t already there
# /swapfile none swap sw 0 0
## Check result:
# grep SwapTotal /proc/meminfo