#################################################
# Gest configurations
#################################################
---
- hosts: web
  become: yes
  vars_files:
    - group_vars/emnies_hosts

  tasks:
    - name: Set APCu
      become: true
      apt:
        name: php7.2-apcu
        update_cache: yes
        state: present
      tags: [apt_apcu]
      register: out
    
    - debug: var=out.stdout_lines
      tags: [apt_apcu]

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php, tags: [ 'php' ] }
    - { role: geerlingguy.mysql, tags: [ 'mysql' ] }
    - { role: geerlingguy.php-mysql, tags: [ 'php-mysql' ] }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.drush }

  post_tasks:
    - name: Restart apache for enabling MySQL
      command: apache2ctl restart
      register: out

    - debug: var=out.stdout_lines

    # @TODO: add Directoy at default host for clean URL:
    # <Directory /var/www/html>
    #   Options Indexes FollowSymLinks MultiViews
    #   AllowOverride All
    #   Require all granted
    # </Directory>
    # /etc/apache2/sites-enabled/000-default.conf
