#################################################
# Host Configurations
#################################################
---
- hosts: host
  vars_files:
    - group_vars/emnies_hosts
  tasks:
    - name: Self ping
      shell: ping 127.0.0.1 -c 1
      register: out

    - debug: var=out.stdout_lines

    - name: Install virtualbox
      become: true
      apt:
        name: virtualbox
        update_cache: yes
        state: present

    # @TODO: install guest additions

    - name: Get vagrant zip and checksum
      get_url:
        url: "{{ vagrant_zip_base_path }}{{ vagrant_zip_file }}"
        dest: /{{ playbook_dir }}/vagrant/{{ vagrant_zip_file }}
        checksum: "{{ vagrant_zip_file_checksum }}"
        force: no

    - name: Unzip vagrant (original is kept)
      unarchive:
        src: /{{ playbook_dir }}/vagrant/{{ vagrant_zip_file }}
        dest: /{{ playbook_dir }}/vagrant
        remote_src: yes

    - name: Remove vagrant source
      file:
        path: /{{ playbook_dir }}/vagrant/{{ vagrant_zip_file }}
        state: absent

    - name: ls
      shell: ls {{ playbook_dir }}/vagrant
      register: out

    - debug: var=out.stdout_lines
