#################################################
# Host Configurations
#################################################
---
- hosts: host
  vars_files:
    - group_vars/emnies_hosts
  tasks:
    - name: Pwd
      shell: pwd
      register: out

    - debug: var=out.stdout_lines
      
    - name: Self ping
      shell: ping 127.0.0.1 -c 1
      register: out

    - debug: var=out.stdout_lines

    - name: Echo
      shell: echo "{{ emnies_host_username }}"
      register: out

    - debug: var=out.stdout_lines
    