# -*- mode: ruby -*-
# vi: set ft=ruby :

# @TODO: use multiple machines: web, db, solr.
# https://www.vagrantup.com/docs/multi-machine/
# https://www.vagrantup.com/docs/networking/private_network.html
# https://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/
# https://technology.amis.nl/2018/07/27/virtualbox-networking-explained/#prettyPhoto
# Define machine, provider and host names:
# https://stackoverflow.com/questions/17845637/how-to-change-vagrant-default-machine-name
# ssh vagrant@127.0.0.1 -p 2222
# cat /etc/environment
# Configuration for Search API for C9/AWS/DIGIT
# Get at admin/config/search/search_api/server/solr_server/edit and configure:
#     HTTP protocol: 
#     Solr Host: 127.0.0.1
#     Solr port: 8983
#     Solr path:  /solr/d7_search_api
# Configuration for Search API for Baremetal/Vagrant
# Get at admin/config/search/search_api/server/solr_server/edit and configure:
#     HTTP protocol: 
#     Solr Host: 127.0.0.1
#     Solr port: 8983
#     Solr path:  /solr/collection1


Vagrant.configure("2") do |config|

  config.vm.define "default", autostart: false do |default|
    default.vm.box = "ubuntu/focal64"
    # default.vm.box = "ubuntu/impish64"
    # @TODO: make the disk size configurable:
    default.disksize.size = '100GB'
    # SSH:
    default.vm.network "forwarded_port", guest: 22, host: 2224
    # Apache from guest in SSL to any IP in host for allowing redirection:
    default.vm.network "forwarded_port", guest: 443, host: 8181, host_ip: "0.0.0.0"    
    # Redirection for xdebug:
    default.vm.network "forwarded_port", guest: 9000, host: 9001, host_ip: "127.0.0.1"
    # Solr by default stays at 8983:
    default.vm.network "forwarded_port", guest: 8983, host: 9191, host_ip: "127.0.0.1"
    # @TODO: do not use network name or get it from a configuration file
    default.vm.network "public_network", bridge: "enp4s0", ip: "192.168.0.222"
    default.vm.synced_folder "data", "/vagrant_data"
    default.vm.provider "virtualbox" do |vb|
      # Dont display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = "6000"
      vb.cpus = "3"
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    default.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end

  config.vm.define "web", autostart: false do |web|
    web.vm.box = "ubuntu/bionic64"
    # @TODO: make the disk size configurable:
    web.disksize.size = '50GB'
    # SSH:
    web.vm.network "forwarded_port", guest: 22, host: 2223
    # Apache from guest to host:
    web.vm.network "forwarded_port", guest: 80, host: 8282, host_ip: "127.0.0.1"
    # @TODO: provide a mapping from http at host to http at guest for allowing
    # provision of locally available files, eg. solr.
    # Solr:
    # web.vm.network "forwarded_port", guest: 8983, host: 9090, host_ip: "127.0.0.1"
    # @TODO: do not use network name or get it automatically of from a configuration file
    web.vm.network "public_network", bridge: "enp4s0", ip: "192.168.0.0"
    #web.vm.network "public_network", ip: "192.168.0.17"

    #web.vm.network "public_network", bridge: [
    #  "enp4s0",
    #  "other-option",
    #]

    web.vm.synced_folder "data_web", "/vagrant_data"
    web.vm.provider "virtualbox" do |vb|
      # Dont display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = "3000"
      vb.cpus = "2"
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    web.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end

  config.vm.define "db", autostart: false do |db|
    db.vm.box = "ubuntu/bionic64"
    # @TODO: make the disk size configurable:
    db.disksize.size = '100GB'
    # SSH:
    db.vm.network "forwarded_port", guest: 22, host: 2224
    # Apache from guest to host:
    db.vm.network "forwarded_port", guest: 80, host: 8282, host_ip: "127.0.0.1"
    # @TODO: provide a mapping from http at host to http at guest for allowing
    # provision of locally available files, eg. solr.
    # @TODO: do not use network name or get it automatically of from a configuration file
    db.vm.network "public_network", bridge: "enp4s0", ip: "192.168.0.1"
    db.vm.synced_folder "data_db", "/vagrant_data"
    db.vm.provider "virtualbox" do |vb|
      # Dont display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = "6000"
      vb.cpus = "3"
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    db.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end

  config.vm.define "solr", autostart: false do |solr|
    solr.vm.box = "ubuntu/bionic64"
    # @TODO: make the disk size configurable:
    solr.disksize.size = '100GB'
    # SSH:
    solr.vm.network "forwarded_port", guest: 22, host: 2225
    # @TODO: provide a mapping from http at host to http at guest for allowing
    # provision of locally available files, eg. solr.
    # Solr:
    solr.vm.network "forwarded_port", guest: 8983, host: 9191, host_ip: "127.0.0.1"
    # @TODO: do not use network name or get it automatically of from a configuration file
    solr.vm.network "public_network", bridge: "enp4s0", ip: "192.168.0.2"
    solr.vm.synced_folder "data_solr", "/vagrant_data"
    solr.vm.provider "virtualbox" do |vb|
      # Dont display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = "6000"
      vb.cpus = "3"
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    solr.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end

end

# sshfs -p 2222 vagrant@127.0.0.1:/var/www/html /home/devlin/baremetal/ansible/vagrant/data/assets/project/code